/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "OTP.EXPIRED": string;
        "OTP.INVALID": string;
    };
    "user": {
        "INVALID_CREDENTIALS": string;
        "ACCOUNT_VERIFICATION_NEEDED": string;
        "NOT_FOUND": string;
        "LOGOUT_SUCCESS": string;
        "LOGOUT_FAILED": string;
        "EMAIL_NOT_FOUND": string;
        "EMAIL_ALREADY_VERIFIED": string;
        "EMAIL_NOT_VERIFIED": string;
        "TWO_FACTOR_ALREADY_ENABLED": string;
        "TWO_FACTOR_ALREADY_DISABLED": string;
        "USER_NOT_FOUND": string;
    };
    "validation": {
        "NOT_EMPTY": string;
        "REQUIRED": string;
        "MIN": string;
        "MAX": string;
        "LENGTH": string;
        "STRING": string;
        "NUMBER": string;
        "INTEGER": string;
        "ARRAY": string;
        "OBJECT": string;
        "DATE": string;
        "BOOLEAN": string;
        "EMAIL": string;
        "ALPHANUMERIC": string;
        "PASSWORD_COMPLEXITY": string;
        "PHONE_NUMBER": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
